Update main.go
dubek/rabbitmq-dump-queue pull request #7
Opened 2017-01-10 13:10 UTC by msteggink

Made acknowledgements configurable.

2017-01-10 13:10 UTC, msteggink commented
My first go, please review. Thanks!

2017-01-10 13:38 UTC, dubek requested changes
Thanks for adding this!

The code change itself looks good except the small formatting issue.

Please add a test to `main_test.go` testing this new feature. For example it can populate a queue with 10 messages, dump 3 messages, then dump 10 more (and expect exactly 7 to be dumped).

Please add a small paragraph to `README.md` explaining the new switch. Using this switch will actually *drain* the queue from the N messages, so in that sense it is a dangerous operation and should be explained as such.

2017-01-10 13:38 UTC, dubek commented on main.go
> +        ack          = flag.Bool("ack", false, "Acknowledge messages")
I think this line is indented with spaces instead of tabs which are recommended by Go style. Please use `go fmt` to format the code.

2017-01-10 15:18 UTC, msteggink commented
The test has been added, please let me know if this is acceptable.

2017-01-15 07:46 UTC, dubek commented
Looks good! Merging.

2017-01-15 07:46 UTC, merged

2017-01-15 07:51 UTC, dubek commented
One last comment (for next time): please make the commit message more descriptive: instead of "update main.go" I'd write something like "Support -ack option for removing messages from queue".

2019-10-06 18:32 UTC, dubek commented
This is now part of release v0.4 available via the [releases page](https://github.com/dubek/rabbitmq-dump-queue/releases).